In [6]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("qoute_dataset.csv")

In [8]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [9]:
df.shape

(3038, 2)

In [10]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [11]:
quotes = quotes.str.lower()

In [12]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [13]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [14]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [15]:
vocab_size = 10000

tokinizer = Tokenizer(num_words=vocab_size)
tokinizer.fit_on_texts(quotes)

In [16]:
word_index = tokinizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [17]:
sequence = tokinizer.texts_to_sequences(quotes)

In [18]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [19]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [20]:
X = []
y = []

for seq in sequence:
  for i in range(1,len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [21]:
len(X)

85271

In [22]:
len(y)

85271

In [23]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [24]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [25]:
y = np.array(y)

In [26]:
X_padded.shape

(85271, 745)

In [27]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [28]:
y.shape

(85271,)

In [29]:
y_one_hot.shape

(85271, 10000)

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,LSTM, Dense

In [31]:
embedding_dim = 50
rnn_units = 128

In [32]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
rnn_model.add(SimpleRNN(units=rnn_units))
rnn_model.add(Dense(units=vocab_size, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [33]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [34]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
lstm_model = Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(units=vocab_size, activation='softmax'))

In [36]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [37]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
epochs = 10
batch_size = 128

In [39]:
history_rnn = rnn_model.fit(
    X_padded, y_one_hot,
    epochs = epochs,
    batch_size = batch_size,
    validation_split = 0.2

)

Epoch 1/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 44s 74ms/step - accuracy: 0.0381 - loss: 6.8714 - val_accuracy: 0.0483 - val_loss: 6.8034
Epoch 2/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 75s 67ms/step - accuracy: 0.0529 - loss: 6.3855 - val_accuracy: 0.0578 - val_loss: 6.7764
Epoch 3/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.0600 - loss: 6.2627 - val_accuracy: 0.0588 - val_loss: 6.7762
Epoch 4/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.0709 - loss: 6.0841 - val_accuracy: 0.0703 - val_loss: 6.7188
Epoch 5/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.0841 - loss: 5.8874 - val_accuracy: 0.0839 - val_loss: 6.6593
Epoch 6/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.0994 - loss: 5.6955 - val_accuracy: 0.0905 - val_loss: 6.6136
Epoch 7/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 67ms/step - accuracy: 0.1093 - loss: 5.5182 - val_accuracy: 0.0923 - val_loss: 6.6061
Epoch 8/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.1178 - loss: 5.3493 - val_accuracy: 0.1017 - val_loss: 6.5967
Epoch 9/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.1284 - loss: 5.1850 - val_accuracy: 0.1030 - val_loss: 6.5986
Epoch 10/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 35s 66ms/step - accuracy: 0.1379 - loss: 5.0245 - val_accuracy: 0.1060 - val_loss: 6.6507

In [40]:
epochs = 100
batch_size = 128
history_lstm = lstm_model.fit(
    X_padded,
    y_one_hot,
    epochs = epochs,
    batch_size = batch_size,
    validation_split = 0.1

)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 56ms/step - accuracy: 0.0398 - loss: 6.7621 - val_accuracy: 0.0410 - val_loss: 6.6808
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.0621 - loss: 6.3002 - val_accuracy: 0.0725 - val_loss: 6.5084
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.0851 - loss: 6.0255 - val_accuracy: 0.0895 - val_loss: 6.4590
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1005 - loss: 5.8103 - val_accuracy: 0.0979 - val_loss: 6.4186
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.1124 - loss: 5.6173 - val_accuracy: 0.1006 - val_loss: 6.3970
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1221 - loss: 5.4442 - val_accuracy: 0.1073 - val_loss: 6.4166
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1312 - loss: 5.2872 - val_accuracy: 0.1082 - val_loss: 6.4391
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1383 - loss: 5.1398 - val_accuracy: 0.1101 - val_loss: 6.4746
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1448 - loss: 5.0010 - val_accuracy: 0.1105 - val_loss: 6.5345
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1513 - loss: 4.8683 - val_accuracy: 0.1114 - val_loss: 6.5766
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1575 - loss: 4.7389 - val_accuracy: 0.1135 - val_loss: 6.6376
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1657 - loss: 4.6137 - val_accuracy: 0.1123 - val_loss: 6.7110
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1749 - loss: 4.4889 - val_accuracy: 0.1116 - val_loss: 6.7727
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.1853 - loss: 4.3690 - val_accuracy: 0.1127 - val_loss: 6.8301
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1971 - loss: 4.2488 - val_accuracy: 0.1107 - val_loss: 6.9117
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2109 - loss: 4.1355 - val_accuracy: 0.1116 - val_loss: 6.9712
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2244 - loss: 4.0251 - val_accuracy: 0.1114 - val_loss: 7.0463
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2376 - loss: 3.9219 - val_accuracy: 0.1108 - val_loss: 7.1357
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2527 - loss: 3.8226 - val_accuracy: 0.1123 - val_loss: 7.2013
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2661 - loss: 3.7294 - val_accuracy: 0.1132 - val_loss: 7.2910
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2794 - loss: 3.6446 - val_accuracy: 0.1088 - val_loss: 7.3579
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2907 - loss: 3.5622 - val_accuracy: 0.1068 - val_loss: 7.4441
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3033 - loss: 3.4872 - val_accuracy: 0.1101 - val_loss: 7.5093
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.3139 - loss: 3.4137 - val_accuracy: 0.1069 - val_loss: 7.5748
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3262 - loss: 3.3431 - val_accuracy: 0.1065 - val_loss: 7.6624
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3363 - loss: 3.2774 - val_accuracy: 0.1041 - val_loss: 7.7350
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.3465 - loss: 3.2139 - val_accuracy: 0.1031 - val_loss: 7.8076
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3582 - loss: 3.1523 - val_accuracy: 0.1053 - val_loss: 7.8711
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3661 - loss: 3.0938 - val_accuracy: 0.1013 - val_loss: 7.9335
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3759 - loss: 3.0375 - val_accuracy: 0.0998 - val_loss: 8.0064
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3852 - loss: 2.9823 - val_accuracy: 0.1000 - val_loss: 8.0701
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.3941 - loss: 2.9283 - val_accuracy: 0.0991 - val_loss: 8.1287
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4022 - loss: 2.8762 - val_accuracy: 0.1035 - val_loss: 8.1967
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4108 - loss: 2.8273 - val_accuracy: 0.0998 - val_loss: 8.2572
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4202 - loss: 2.7775 - val_accuracy: 0.0978 - val_loss: 8.3132
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4287 - loss: 2.7324 - val_accuracy: 0.1000 - val_loss: 8.3897
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4353 - loss: 2.6862 - val_accuracy: 0.0966 - val_loss: 8.4501
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 53ms/step - accuracy: 0.4436 - loss: 2.6431 - val_accuracy: 0.0966 - val_loss: 8.5188
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4516 - loss: 2.6011 - val_accuracy: 0.0967 - val_loss: 8.5624
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.4585 - loss: 2.5595 - val_accuracy: 0.0977 - val_loss: 8.6364
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4666 - loss: 2.5153 - val_accuracy: 0.0960 - val_loss: 8.6902
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4746 - loss: 2.4753 - val_accuracy: 0.0920 - val_loss: 8.7504
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4815 - loss: 2.4376 - val_accuracy: 0.0937 - val_loss: 8.8165
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4888 - loss: 2.3992 - val_accuracy: 0.0925 - val_loss: 8.8699
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4952 - loss: 2.3634 - val_accuracy: 0.0912 - val_loss: 8.9386
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5018 - loss: 2.3286 - val_accuracy: 0.0904 - val_loss: 8.9876
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5079 - loss: 2.2922 - val_accuracy: 0.0922 - val_loss: 9.0283
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.5148 - loss: 2.2597 - val_accuracy: 0.0899 - val_loss: 9.0977
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5224 - loss: 2.2250 - val_accuracy: 0.0918 - val_loss: 9.1585
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 53ms/step - accuracy: 0.5287 - loss: 2.1926 - val_accuracy: 0.0903 - val_loss: 9.2244
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5342 - loss: 2.1607 - val_accuracy: 0.0892 - val_loss: 9.2798
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5397 - loss: 2.1297 - val_accuracy: 0.0879 - val_loss: 9.3211
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5469 - loss: 2.1002 - val_accuracy: 0.0891 - val_loss: 9.3846
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 53ms/step - accuracy: 0.5527 - loss: 2.0697 - val_accuracy: 0.0874 - val_loss: 9.4531
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5590 - loss: 2.0406 - val_accuracy: 0.0851 - val_loss: 9.4985
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5645 - loss: 2.0133 - val_accuracy: 0.0869 - val_loss: 9.5316
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5691 - loss: 1.9855 - val_accuracy: 0.0875 - val_loss: 9.5924
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5743 - loss: 1.9584 - val_accuracy: 0.0862 - val_loss: 9.6546
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.5802 - loss: 1.9313 - val_accuracy: 0.0856 - val_loss: 9.7143
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5846 - loss: 1.9064 - val_accuracy: 0.0834 - val_loss: 9.7492
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5904 - loss: 1.8792 - val_accuracy: 0.0854 - val_loss: 9.8078
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5952 - loss: 1.8555 - val_accuracy: 0.0830 - val_loss: 9.8687
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5997 - loss: 1.8334 - val_accuracy: 0.0840 - val_loss: 9.9141
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6056 - loss: 1.8083 - val_accuracy: 0.0822 - val_loss: 9.9845
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6091 - loss: 1.7855 - val_accuracy: 0.0829 - val_loss: 10.0251
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6152 - loss: 1.7622 - val_accuracy: 0.0811 - val_loss: 10.0893
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6195 - loss: 1.7407 - val_accuracy: 0.0830 - val_loss: 10.1338
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6238 - loss: 1.7175 - val_accuracy: 0.0838 - val_loss: 10.1818
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6280 - loss: 1.6972 - val_accuracy: 0.0851 - val_loss: 10.2186
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6329 - loss: 1.6762 - val_accuracy: 0.0810 - val_loss: 10.2554
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6367 - loss: 1.6559 - val_accuracy: 0.0823 - val_loss: 10.3581
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6413 - loss: 1.6359 - val_accuracy: 0.0796 - val_loss: 10.3748
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6436 - loss: 1.6178 - val_accuracy: 0.0796 - val_loss: 10.4429
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6495 - loss: 1.5970 - val_accuracy: 0.0811 - val_loss: 10.4687
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6532 - loss: 1.5779 - val_accuracy: 0.0793 - val_loss: 10.5061
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6572 - loss: 1.5605 - val_accuracy: 0.0810 - val_loss: 10.5656
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6610 - loss: 1.5429 - val_accuracy: 0.0795 - val_loss: 10.6316
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6654 - loss: 1.5229 - val_accuracy: 0.0788 - val_loss: 10.6660
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6692 - loss: 1.5075 - val_accuracy: 0.0794 - val_loss: 10.7343
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6716 - loss: 1.4894 - val_accuracy: 0.0754 - val_loss: 10.7615
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6775 - loss: 1.4723 - val_accuracy: 0.0783 - val_loss: 10.8004
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6797 - loss: 1.4575 - val_accuracy: 0.0789 - val_loss: 10.8963
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6826 - loss: 1.4406 - val_accuracy: 0.0766 - val_loss: 10.9044
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6857 - loss: 1.4248 - val_accuracy: 0.0788 - val_loss: 10.9789
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6891 - loss: 1.4092 - val_accuracy: 0.0775 - val_loss: 11.0402
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6932 - loss: 1.3934 - val_accuracy: 0.0772 - val_loss: 11.0622
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6959 - loss: 1.3781 - val_accuracy: 0.0767 - val_loss: 11.1008
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.6996 - loss: 1.3640 - val_accuracy: 0.0774 - val_loss: 11.1502
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7024 - loss: 1.3495 - val_accuracy: 0.0776 - val_loss: 11.2029
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7047 - loss: 1.3358 - val_accuracy: 0.0765 - val_loss: 11.2339
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7081 - loss: 1.3216 - val_accuracy: 0.0761 - val_loss: 11.2988
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7116 - loss: 1.3075 - val_accuracy: 0.0731 - val_loss: 11.3389
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7143 - loss: 1.2937 - val_accuracy: 0.0753 - val_loss: 11.4003
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7163 - loss: 1.2799 - val_accuracy: 0.0745 - val_loss: 11.4291
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7212 - loss: 1.2674 - val_accuracy: 0.0747 - val_loss: 11.4724
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7220 - loss: 1.2552 - val_accuracy: 0.0754 - val_loss: 11.5254
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7260 - loss: 1.2423 - val_accuracy: 0.0739 - val_loss: 11.5607
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7278 - loss: 1.2284 - val_accuracy: 0.0754 - val_loss: 11.6057
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7307 - loss: 1.2207 - val_accuracy: 0.0734 - val_loss: 11.6620
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7332 - loss: 1.2063 - val_accuracy: 0.0754 - val_loss: 11.6889